// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrabalhandoComTasks.Data.Contexts;

namespace TrabalhandoComTasks.Migrations
{
    [DbContext(typeof(TasksContext))]
    [Migration("20200424230725_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrabalhandoComTasks.Domain.Entities.GrupoPessoa", b =>
                {
                    b.Property<int>("IdGrupoPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idGrupoPessoa")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeGrupo")
                        .HasColumnName("nomeGrupo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGrupoPessoa")
                        .HasName("pk_grupoPessoa");

                    b.ToTable("GrupoPessoa");
                });

            modelBuilder.Entity("TrabalhandoComTasks.Domain.Entities.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idPessoa")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdGrupoPessoa")
                        .HasColumnName("idGrupoPessoa")
                        .HasColumnType("int");

                    b.Property<string>("NomePessoa")
                        .HasColumnName("nomePessoa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPessoa")
                        .HasName("pk_pessoa");

                    b.HasIndex("IdGrupoPessoa");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("TrabalhandoComTasks.Domain.Entities.Pessoa", b =>
                {
                    b.HasOne("TrabalhandoComTasks.Domain.Entities.GrupoPessoa", "GrupoPessoa")
                        .WithMany("Pessoas")
                        .HasForeignKey("IdGrupoPessoa")
                        .HasConstraintName("fk_pessoa_grupoPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TrabalhandoComTasks.Domain.ValueObjects.Documento", "Documento", b1 =>
                        {
                            b1.Property<int>("PessoaIdPessoa")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("NumeroDocumento")
                                .HasColumnName("numeroDocumento")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TipoDocumento")
                                .HasColumnName("tipoDocumento")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PessoaIdPessoa");

                            b1.ToTable("Pessoa");

                            b1.WithOwner()
                                .HasForeignKey("PessoaIdPessoa");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
